interface Post {
  id: number
  itemid: number
  shopid: number
  currency: string
  stock: number
  status: number
  sold: number
  liked_count: number
  catid: number
  cmt_count: number
  discount: string
  raw_discount: number
  size_chart: string
  shop_name: string
  transparent_background_image: string
  images: string
  view_count: number
  name: string
  image: string
  price: number
  price_min: number
  price_max: number
  historical_sold: number
  price_min_before_discount: number
  price_max_before_discount: number
  shop_rating: number
  filename: string
  liked: boolean
  ctime: Date
  show_free_shipping: boolean
  is_video: boolean
  is_attributes: boolean
  createdAt: Date
  updatedAt: Date
}
